/**
 * Which real street is the circuit on, at every point of the lap?
 *
 * The Overture road layer carries names, and the circuit was drawn over real Dogpatch streets,
 * so the answer is derivable rather than invented: match each track sample to the nearest named
 * roadway and collapse the runs. Emits src/track/streets.js, a table of (arc-length, name) the
 * game reads to sign its own corners.
 *
 *   node tools/streets.mjs
 */
import fs from 'node:fs';
import { World } from '../src/world/world.js';
import { buildTrack } from '../src/track/track.js';

const json = JSON.parse(fs.readFileSync('public/data/world.json', 'utf8'));
const heights = new Float32Array(fs.readFileSync('public/data/world-height.bin').buffer);
const world = new World(json, heights);
const track = buildTrack(world);

function segDist(px, pz, a, b) {
  const vx = b[0] - a[0], vz = b[1] - a[1];
  const wx = px - a[0], wz = pz - a[1];
  const L = vx * vx + vz * vz;
  const t = L ? Math.max(0, Math.min(1, (wx * vx + wz * vz) / L)) : 0;
  return Math.hypot(wx - vx * t, wz - vz * t);
}

const STEP = 4;                                  // metres between probes
const named = json.roads.filter(r => r.name);
const hits = [];
for (let s = 0; s < track.length; s += STEP) {
  const m = track.sample(s);
  let best = null, bd = 30;                      // beyond 30 m it is not that street
  for (const r of named) {
    for (const path of r.paths) {
      for (let i = 0; i < path.length - 1; i++) {
        const d = segDist(m.pos.x, m.pos.z, path[i], path[i + 1]);
        if (d < bd) { bd = d; best = r.name; }
      }
    }
  }
  hits.push({ s, name: best });
}

// collapse to runs, dropping anything too short to be a real leg
const runs = [];
for (const h of hits) {
  const last = runs[runs.length - 1];
  if (last && last.name === h.name) last.end = h.s;
  else runs.push({ name: h.name, start: h.s, end: h.s });
}
/* Drop the noise BEFORE merging, not after.
 *
 * A gap between two runs of the same street is an intersection, or a few probes where the
 * circuit swings wide of the roadway it is plainly still on. But the gap is often filled by a
 * short run naming the CROSS street, and merging first leaves that spurious run sitting between
 * two halves of one leg, blocking the join — which is why the first pass reported the same
 * street six times instead of once. */
const solid = runs.filter(r => r.name && r.end - r.start >= 24);
const merged = [];
for (const r of solid) {
  const last = merged[merged.length - 1];
  if (last && last.name === r.name && r.start - last.end <= 90) last.end = r.end;
  else merged.push({ ...r });
}
const legs = merged.filter(r => r.end - r.start >= 40);

console.log(`circuit ${track.length.toFixed(0)} m, ${legs.length} named legs:`);
for (const l of legs) console.log(`  ${l.start.toFixed(0).padStart(5)}-${l.end.toFixed(0).padStart(5)} m  ${l.name}`);

const body = legs.map(l => `  { s: ${l.start.toFixed(1)}, end: ${l.end.toFixed(1)}, name: ${JSON.stringify(l.name)} },`).join('\n');
fs.writeFileSync('src/track/streets.js', `/**
 * The circuit's real street names, by arc-length.
 *
 * GENERATED by tools/streets.mjs — do not hand-edit. Each leg is the stretch of lap where the
 * nearest named roadway in the Overture data is that street, which is the honest answer to
 * "where am I?" because the circuit was drawn over these streets in the first place.
 *
 * Dogpatch reads as a loop of Illinois, 20th, Indiana, 22nd, Tennessee and 23rd.
 */
export const LEGS = [
${body}
];

/** The street under a given arc-length position, or null between legs. */
export function streetAt(s, length) {
  const t = ((s % length) + length) % length;
  for (const l of LEGS) if (t >= l.s && t <= l.end) return l.name;
  return null;
}
`);
console.log('\nwrote src/track/streets.js');
