/**
 * The circuit's real street names, by arc-length.
 *
 * GENERATED by tools/streets.mjs — do not hand-edit. Each leg is the stretch of lap where the
 * nearest named roadway in the Overture data is that street, which is the honest answer to
 * "where am I?" because the circuit was drawn over these streets in the first place.
 *
 * Dogpatch reads as a loop of Illinois, 20th, Indiana, 22nd, Tennessee and 23rd.
 */
export const LEGS = [
  { s: 0.0, end: 532.0, name: "Illinois Street" },
  { s: 536.0, end: 864.0, name: "20th Street" },
  { s: 868.0, end: 1136.0, name: "Indiana Street" },
  { s: 1140.0, end: 1288.0, name: "22nd Street" },
  { s: 1292.0, end: 1556.0, name: "Tennessee Street" },
  { s: 1560.0, end: 1704.0, name: "23rd Street" },
];

/** The street under a given arc-length position, or null between legs. */
export function streetAt(s, length) {
  const t = ((s % length) + length) % length;
  for (const l of LEGS) if (t >= l.s && t <= l.end) return l.name;
  return null;
}
